#!/usr/bin/env python3
# Offline KAT generator. Dev-only: regenerates tests/kat_vectors.rs and
# tests/kat_vectors_framed.rs.
# Requires a PINNED reedsolo for reproducible vectors: `pip install reedsolo==1.7.0`.
# NOT a build/test/runtime dependency. The committed fixture files are the
# source of truth for cargo; this script only regenerates them.
import binascii
import struct
import subprocess

import reedsolo

# Print the reedsolo version the fixture was generated with (reproducibility).
print(f"[gen_kat] reedsolo {getattr(reedsolo, '__version__', 'unknown')}")

# Output fixture paths and the rustfmt edition used to normalize them.
OUTPUT_PATH = "tests/kat_vectors.rs"
FRAMED_OUTPUT_PATH = "tests/kat_vectors_framed.rs"
RUSTFMT_EDITION = "2021"


def codec(nsym, nsize):
    return reedsolo.RSCodec(nsym, fcr=112, prim=0x187, generator=2, c_exp=8, nsize=nsize)


def fmt(name, data):
    body = ", ".join(str(b) for b in data)
    return f"pub const {name}: &[u8] = &[{body}];\n"


def emit(prefix, data_len, parity, sample, err_positions, over_positions):
    n = data_len + parity
    rs = codec(parity, n)
    enc = bytearray(rs.encode(bytes(sample)))
    corrupted = bytearray(enc)
    for p in err_positions:
        corrupted[p] ^= 0x5A
    over = bytearray(enc)
    for p in over_positions:
        over[p] ^= 0xA5
    # self-check the reference round-trips (param sanity) before emitting vectors
    assert bytes(rs.decode(bytes(corrupted))[0]) == bytes(sample), f"{prefix}: must recover"
    try:
        rs.decode(bytes(over))
        raise AssertionError(f"{prefix}: over-capacity must fail")
    except reedsolo.ReedSolomonError:
        pass
    out = ""
    out += fmt(f"{prefix}_DATA", sample)
    out += fmt(f"{prefix}_ENCODED", enc)
    out += fmt(f"{prefix}_CORRUPTED", corrupted)
    out += fmt(f"{prefix}_DECODED", sample)            # expected decode result
    out += fmt(f"{prefix}_UNCORRECTABLE", over)
    return out


def emit_framed(prefix, data_len, parity, sample):
    """Emit a framed fixture file (RS255_DATA + RS255_FRAMED) for tests/framed.rs.

    Written to a SEPARATE file (tests/kat_vectors_framed.rs) so that the raw
    KAT file (tests/kat_vectors.rs) does not contain RS255_FRAMED, avoiding
    dead_code warnings in the kat test binary which does not use it.

    The header layout mirrors ``src/frame.rs``:
        magic(2) + version(1) + parity(1) + data_len(1) + orig_len_be_u64(8)
        + crc32_ieee_be_u32(4) over the preceding 13 bytes.
    ``binascii.crc32`` is CRC-32/IEEE (check value 0xCBF43926) -- identical
    to the Rust ``src/crc.rs`` implementation.
    """
    n = data_len + parity
    rs = codec(parity, n)
    body = bytes(rs.encode(bytes(sample)))
    header = bytes([0x52, 0x53, 1, parity, data_len]) + struct.pack(">Q", len(sample))
    header += struct.pack(">I", binascii.crc32(header) & 0xFFFFFFFF)
    # Emit both DATA (so framed.rs need not depend on kat_vectors.rs) and FRAMED.
    out = ""
    out += fmt(f"{prefix}_DATA", sample)
    out += fmt(f"{prefix}_FRAMED", header + body)
    return out


def main():
    # --- Raw encode/decode KAT vectors (tests/kat_vectors.rs) ---
    header = "// GENERATED by scripts/gen_kat.py (reedsolo, fcr=112 prim=0x187 gen=2). Do not edit.\n\n"
    body = ""
    body += emit("RS255", 223, 32, list(range(223)), list(range(0, 48, 3)), list(range(40)))
    body += emit("RS15", 11, 4, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], [2, 9], [0, 1, 2, 3, 4])
    # odd parity (t=1) -- exercises floor(parity/2) and odd-root generator
    body += emit("RS13", 10, 3, [10, 20, 30, 40, 50, 60, 70, 80, 90, 100], [4], [0, 1, 2, 3])
    with open(OUTPUT_PATH, "w", newline="\n") as f:
        f.write(header + body)
    subprocess.run(["rustfmt", "--edition", RUSTFMT_EDITION, OUTPUT_PATH], check=True)
    print(f"[gen_kat] wrote and rustfmt-normalized {OUTPUT_PATH}")

    # --- Framed KAT vectors (tests/kat_vectors_framed.rs) ---
    # Kept separate to avoid dead_code warnings in the kat binary (which does
    # not use RS255_FRAMED) and in the framed binary (which only needs these two).
    framed_header = "// GENERATED by scripts/gen_kat.py (reedsolo, fcr=112 prim=0x187 gen=2). Do not edit.\n\n"
    framed_body = emit_framed("RS255", 223, 32, list(range(223)))
    with open(FRAMED_OUTPUT_PATH, "w", newline="\n") as f:
        f.write(framed_header + framed_body)
    subprocess.run(["rustfmt", "--edition", RUSTFMT_EDITION, FRAMED_OUTPUT_PATH], check=True)
    print(f"[gen_kat] wrote and rustfmt-normalized {FRAMED_OUTPUT_PATH}")


if __name__ == "__main__":
    main()